name: build and Deploy site
on:
  push:
    branches:
      - main
env:
  CI: false
jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: npm install
        working-directory: ./
      - run: npm run build
        working-directory: ./

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d--%H-%M')" >> $GITHUB_OUTPUT

      - name: Pack build
        run: |
          tar -czvf site-${{ steps.date.outputs.date }}.tar.gz -C ./build/ .
          cp site-* site-latest.tar.gz

      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "*.tar.gz"
          target: ${{ secrets.SERVER_PATH_BUILDS }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: bash ${{ secrets.SERVER_PATH_SCRIPTS }}/site-deploy.sh
